using System.Collections.Generic;
using EternalEnigma.Core.Classes;

namespace EternalEnigma.Tests
{
    // Expected Phase 7 content. Mirrors Docs/Classes.md and the ClassContent_* generators.
    internal static class ClassContentExpectations
    {
        public sealed class Row
        {
            public Row(string classId, string name, int tier, SkillKind kind, int maxRank)
            { ClassId = classId; Name = name; Tier = tier; Kind = kind; MaxRank = maxRank; }
            public string ClassId { get; }
            public string Name { get; }
            public int Tier { get; }
            public SkillKind Kind { get; }
            public int MaxRank { get; }
        }

        public static readonly string[] ClassIds =
            { "warrior", "guardian", "archer", "elementalist", "healer", "bard", "occultist", "rogue", "commander", "scout" };

        // Skills that are one shared asset across classes (their LearnCost is not tier-based).
        public static readonly HashSet<string> SharedSkills = new() { "Mining", "Harvesting", "Foraging", "SP Up", "Vigor", "HP Up" };

        public static readonly IReadOnlyList<Row> Rows = new[]
        {
            new Row("warrior", "Warrior Novice Training", 1, SkillKind.Mastery, 1),
            new Row("warrior", "Mining", 1, SkillKind.Gathering, 1),
            new Row("warrior", "Double Strike", 1, SkillKind.Normal, 5),
            new Row("warrior", "Vanguard", 1, SkillKind.Normal, 5),
            new Row("warrior", "Power Boost", 1, SkillKind.Normal, 5),
            new Row("warrior", "Iron Skin", 1, SkillKind.Normal, 5),
            new Row("warrior", "Warrior Adept Training", 2, SkillKind.Mastery, 1),
            new Row("warrior", "Cleave", 2, SkillKind.Normal, 5),
            new Row("warrior", "Piercing Thrust", 2, SkillKind.Normal, 5),
            new Row("warrior", "Initiative", 2, SkillKind.SingleRank, 1),
            new Row("warrior", "Sunder", 2, SkillKind.Normal, 5),
            new Row("warrior", "Rattle", 2, SkillKind.Normal, 5),
            new Row("warrior", "Flame Follow-up", 2, SkillKind.Normal, 5),
            new Row("warrior", "Frost Follow-up", 2, SkillKind.Normal, 5),
            new Row("warrior", "Shock Follow-up", 2, SkillKind.Normal, 5),
            new Row("warrior", "Warrior Master Training", 3, SkillKind.Mastery, 1),
            new Row("warrior", "Whirlwind", 3, SkillKind.Normal, 5),
            new Row("warrior", "Lunge", 3, SkillKind.Normal, 5),
            new Row("warrior", "Improved Follow-ups", 3, SkillKind.SingleRank, 1),
            new Row("warrior", "Follow-up Mastery", 3, SkillKind.SingleRank, 1),
            new Row("guardian", "Guardian Novice Training", 1, SkillKind.Mastery, 1),
            new Row("guardian", "Mining", 1, SkillKind.Gathering, 1),
            new Row("guardian", "HP Up", 1, SkillKind.Normal, 5),
            new Row("guardian", "Provoke", 1, SkillKind.Normal, 5),
            new Row("guardian", "Shield Smite", 1, SkillKind.Normal, 5),
            new Row("guardian", "Defense Boost", 1, SkillKind.Normal, 5),
            new Row("guardian", "Rally", 1, SkillKind.Normal, 1),
            new Row("guardian", "Guardian Adept Training", 2, SkillKind.Mastery, 1),
            new Row("guardian", "HP Regen", 2, SkillKind.Normal, 3),
            new Row("guardian", "Last Stand", 2, SkillKind.Normal, 5),
            new Row("guardian", "Cover", 2, SkillKind.Normal, 5),
            new Row("guardian", "Shield Bash", 2, SkillKind.Normal, 5),
            new Row("guardian", "Flame Barrier", 2, SkillKind.Normal, 5),
            new Row("guardian", "Frost Barrier", 2, SkillKind.Normal, 5),
            new Row("guardian", "Storm Barrier", 2, SkillKind.Normal, 5),
            new Row("guardian", "Guardian Master Training", 3, SkillKind.Mastery, 1),
            new Row("guardian", "Parry Stance", 3, SkillKind.Normal, 5),
            new Row("guardian", "Bulwark", 3, SkillKind.Normal, 5),
            new Row("guardian", "Sanctuary Wall", 3, SkillKind.Normal, 5),
            new Row("guardian", "Aegis", 3, SkillKind.SingleRank, 1),
            new Row("archer", "Archer Novice Training", 1, SkillKind.Mastery, 1),
            new Row("archer", "Foraging", 1, SkillKind.Gathering, 1),
            new Row("archer", "Aimed Shot", 1, SkillKind.Normal, 5),
            new Row("archer", "Pinning Shot", 1, SkillKind.Normal, 5),
            new Row("archer", "Disarming Shot", 1, SkillKind.Normal, 5),
            new Row("archer", "Stunning Shot", 1, SkillKind.Normal, 5),
            new Row("archer", "Keen Eye", 1, SkillKind.Normal, 5),
            new Row("archer", "Archer Adept Training", 2, SkillKind.Mastery, 1),
            new Row("archer", "Longshot", 2, SkillKind.Normal, 5),
            new Row("archer", "Volley", 2, SkillKind.Normal, 5),
            new Row("archer", "Multishot", 2, SkillKind.Normal, 5),
            new Row("archer", "Venom Arrow", 2, SkillKind.Normal, 5),
            new Row("archer", "Sleep Arrow", 2, SkillKind.Normal, 5),
            new Row("archer", "Retreat Shot", 2, SkillKind.Normal, 5),
            new Row("archer", "Deadeye", 2, SkillKind.Normal, 5),
            new Row("archer", "Archer Master Training", 3, SkillKind.Mastery, 1),
            new Row("archer", "Rain of Arrows", 3, SkillKind.Normal, 5),
            new Row("archer", "Piercing Arrow", 3, SkillKind.Normal, 5),
            new Row("archer", "Double Shot", 3, SkillKind.Normal, 5),
            new Row("archer", "Arrow Recovery", 3, SkillKind.Normal, 5),
            new Row("elementalist", "Elementalist Novice Training", 1, SkillKind.Mastery, 1),
            new Row("elementalist", "Harvesting", 1, SkillKind.Gathering, 1),
            new Row("elementalist", "Fire Bolt", 1, SkillKind.Normal, 5),
            new Row("elementalist", "Ice Bolt", 1, SkillKind.Normal, 5),
            new Row("elementalist", "Lightning Bolt", 1, SkillKind.Normal, 5),
            new Row("elementalist", "SP Up", 1, SkillKind.Normal, 5),
            new Row("elementalist", "Focus", 1, SkillKind.Normal, 5),
            new Row("elementalist", "Elementalist Adept Training", 2, SkillKind.Mastery, 1),
            new Row("elementalist", "Fireball", 2, SkillKind.Normal, 5),
            new Row("elementalist", "Blizzard", 2, SkillKind.Normal, 5),
            new Row("elementalist", "Thunderclap", 2, SkillKind.Normal, 5),
            new Row("elementalist", "Expose", 2, SkillKind.Normal, 5),
            new Row("elementalist", "Amplify", 2, SkillKind.Normal, 1),
            new Row("elementalist", "Mana Flow", 2, SkillKind.Normal, 5),
            new Row("elementalist", "Elementalist Master Training", 3, SkillKind.Mastery, 1),
            new Row("elementalist", "Inferno", 3, SkillKind.Normal, 5),
            new Row("elementalist", "Glacier", 3, SkillKind.Normal, 5),
            new Row("elementalist", "Tempest", 3, SkillKind.Normal, 5),
            new Row("elementalist", "Elemental Mastery", 3, SkillKind.Normal, 5),
            new Row("elementalist", "Spell Echo", 3, SkillKind.Normal, 5),
            new Row("healer", "Healer Novice Training", 1, SkillKind.Mastery, 1),
            new Row("healer", "Harvesting", 1, SkillKind.Gathering, 1),
            new Row("healer", "Heal", 1, SkillKind.Normal, 5),
            new Row("healer", "Healing Touch", 1, SkillKind.Normal, 5),
            new Row("healer", "Cure", 1, SkillKind.Normal, 1),
            new Row("healer", "Unbind", 1, SkillKind.Normal, 1),
            new Row("healer", "Healer Adept Training", 2, SkillKind.Mastery, 1),
            new Row("healer", "Group Heal", 2, SkillKind.Normal, 5),
            new Row("healer", "Revive", 2, SkillKind.Normal, 1),
            new Row("healer", "Renew", 2, SkillKind.Normal, 5),
            new Row("healer", "Triage", 2, SkillKind.Normal, 5),
            new Row("healer", "Field Medicine", 2, SkillKind.Normal, 5),
            new Row("healer", "Heavy Strike", 2, SkillKind.Normal, 5),
            new Row("healer", "Healer Master Training", 3, SkillKind.Mastery, 1),
            new Row("healer", "Full Heal", 3, SkillKind.Normal, 5),
            new Row("healer", "Mass Cure", 3, SkillKind.Normal, 1),
            new Row("healer", "Second Wind", 3, SkillKind.SingleRank, 1),
            new Row("healer", "Mass Revive", 3, SkillKind.Normal, 1),
            new Row("healer", "Meditation", 3, SkillKind.Normal, 5),
            new Row("healer", "Vitality", 3, SkillKind.Normal, 5),
            new Row("bard", "Bard Novice Training", 1, SkillKind.Mastery, 1),
            new Row("bard", "Foraging", 1, SkillKind.Gathering, 1),
            new Row("bard", "Battle Hymn", 1, SkillKind.Normal, 3),
            new Row("bard", "Ballad of Stone", 1, SkillKind.Normal, 3),
            new Row("bard", "Soothing Melody", 1, SkillKind.Normal, 3),
            new Row("bard", "Nimble", 1, SkillKind.Normal, 5),
            new Row("bard", "Bard Adept Training", 2, SkillKind.Mastery, 1),
            new Row("bard", "Evasive Rhythm", 2, SkillKind.Normal, 3),
            new Row("bard", "Quickstep", 2, SkillKind.Normal, 1),
            new Row("bard", "Encore", 2, SkillKind.Normal, 3),
            new Row("bard", "Blade Dance", 2, SkillKind.Normal, 5),
            new Row("bard", "Discord", 2, SkillKind.Normal, 1),
            new Row("bard", "War Drums", 2, SkillKind.Normal, 5),
            new Row("bard", "Bard Master Training", 3, SkillKind.Mastery, 1),
            new Row("bard", "Grand Finale", 3, SkillKind.Normal, 3),
            new Row("bard", "Crescendo", 3, SkillKind.SingleRank, 1),
            new Row("bard", "Harmony", 3, SkillKind.SingleRank, 1),
            new Row("bard", "Rousing Chorus", 3, SkillKind.Normal, 5),
            new Row("bard", "Stage Presence", 3, SkillKind.SingleRank, 1),
            new Row("bard", "Vigor", 3, SkillKind.Normal, 5),
            new Row("occultist", "Occultist Novice Training", 1, SkillKind.Mastery, 1),
            new Row("occultist", "Harvesting", 1, SkillKind.Gathering, 1),
            new Row("occultist", "Venom Hex", 1, SkillKind.Normal, 5),
            new Row("occultist", "Paralysis Hex", 1, SkillKind.Normal, 5),
            new Row("occultist", "Slumber Hex", 1, SkillKind.Normal, 5),
            new Row("occultist", "Enfeeble", 1, SkillKind.Normal, 5),
            new Row("occultist", "Occultist Adept Training", 2, SkillKind.Mastery, 1),
            new Row("occultist", "Curse", 2, SkillKind.Normal, 5),
            new Row("occultist", "Terror", 2, SkillKind.Normal, 5),
            new Row("occultist", "Silence Hex", 2, SkillKind.Normal, 5),
            new Row("occultist", "Malice", 2, SkillKind.Normal, 5),
            new Row("occultist", "Lingering Hex", 2, SkillKind.SingleRank, 1),
            new Row("occultist", "Blinding Mist", 2, SkillKind.Normal, 5),
            new Row("occultist", "Exploit", 2, SkillKind.Normal, 5),
            new Row("occultist", "Occultist Master Training", 3, SkillKind.Mastery, 1),
            new Row("occultist", "Plague", 3, SkillKind.Normal, 1),
            new Row("occultist", "Dominate", 3, SkillKind.Normal, 1),
            new Row("occultist", "Siphon", 3, SkillKind.Normal, 5),
            new Row("occultist", "SP Up", 3, SkillKind.Normal, 5),
            new Row("occultist", "Grim Harvest", 3, SkillKind.Normal, 5),
            new Row("rogue", "Rogue Novice Training", 1, SkillKind.Mastery, 1),
            new Row("rogue", "Foraging", 1, SkillKind.Gathering, 1),
            new Row("rogue", "Shadow Step", 1, SkillKind.Normal, 5),
            new Row("rogue", "Smoke Bomb", 1, SkillKind.Normal, 5),
            new Row("rogue", "Evasion", 1, SkillKind.Normal, 5),
            new Row("rogue", "Hamstring", 1, SkillKind.Normal, 5),
            new Row("rogue", "Rogue Adept Training", 2, SkillKind.Mastery, 1),
            new Row("rogue", "Swiftness", 2, SkillKind.Normal, 5),
            new Row("rogue", "Clone", 2, SkillKind.Normal, 3),
            new Row("rogue", "Vanish", 2, SkillKind.Normal, 5),
            new Row("rogue", "Ambush", 2, SkillKind.Normal, 5),
            new Row("rogue", "Caltrops", 2, SkillKind.Normal, 5),
            new Row("rogue", "Ember Scroll", 2, SkillKind.Normal, 5),
            new Row("rogue", "Throat Strike", 2, SkillKind.Normal, 5),
            new Row("rogue", "Rogue Master Training", 3, SkillKind.Mastery, 1),
            new Row("rogue", "Shadow Dance", 3, SkillKind.Normal, 5),
            new Row("rogue", "Twin Shadows", 3, SkillKind.SingleRank, 1),
            new Row("rogue", "Assassinate", 3, SkillKind.Normal, 5),
            new Row("rogue", "Escape Artist", 3, SkillKind.SingleRank, 1),
            new Row("rogue", "Blinding Flash", 3, SkillKind.Normal, 5),
            new Row("commander", "Commander Novice Training", 1, SkillKind.Mastery, 1),
            new Row("commander", "Mining", 1, SkillKind.Gathering, 1),
            new Row("commander", "Command: Attack", 1, SkillKind.Normal, 3),
            new Row("commander", "Command: Guard", 1, SkillKind.Normal, 3),
            new Row("commander", "Blazing Arms", 1, SkillKind.Normal, 3),
            new Row("commander", "Frost Arms", 1, SkillKind.Normal, 3),
            new Row("commander", "Storm Arms", 1, SkillKind.Normal, 3),
            new Row("commander", "Commander Adept Training", 2, SkillKind.Mastery, 1),
            new Row("commander", "Reinforce", 2, SkillKind.SingleRank, 1),
            new Row("commander", "Rally Cry", 2, SkillKind.Normal, 1),
            new Row("commander", "Inspire", 2, SkillKind.Normal, 5),
            new Row("commander", "Command: Endure", 2, SkillKind.Normal, 3),
            new Row("commander", "Aura of Command", 2, SkillKind.Normal, 5),
            new Row("commander", "Command: Advance", 2, SkillKind.Normal, 1),
            new Row("commander", "Commander Master Training", 3, SkillKind.Mastery, 1),
            new Row("commander", "Decisive Order", 3, SkillKind.Normal, 1),
            new Row("commander", "Leadership", 3, SkillKind.SingleRank, 1),
            new Row("commander", "Command: Hold", 3, SkillKind.Normal, 3),
            new Row("commander", "Royal Bearing", 3, SkillKind.Normal, 5),
            new Row("commander", "Vigor", 3, SkillKind.Normal, 5),
            new Row("scout", "Scout Novice Training", 1, SkillKind.Mastery, 1),
            new Row("scout", "Survey", 1, SkillKind.Gathering, 1),
            new Row("scout", "Trap Sense", 1, SkillKind.Normal, 5),
            new Row("scout", "Disarm", 1, SkillKind.Normal, 5),
            new Row("scout", "Pathfinder", 1, SkillKind.Normal, 5),
            new Row("scout", "Floor Sense", 1, SkillKind.Normal, 1),
            new Row("scout", "Scout Adept Training", 2, SkillKind.Mastery, 1),
            new Row("scout", "Soft Step", 2, SkillKind.SingleRank, 1),
            new Row("scout", "Resourceful", 2, SkillKind.Normal, 5),
            new Row("scout", "Throwing Arm", 2, SkillKind.Normal, 5),
            new Row("scout", "Retreat", 2, SkillKind.Normal, 1),
            new Row("scout", "Take Point", 2, SkillKind.SingleRank, 1),
            new Row("scout", "Safe Passage", 2, SkillKind.Normal, 5),
            new Row("scout", "Scout Master Training", 3, SkillKind.Mastery, 1),
            new Row("scout", "Grapple Line", 3, SkillKind.Normal, 1),
            new Row("scout", "Treasure Hunter", 3, SkillKind.SingleRank, 1),
            new Row("scout", "Scavenger", 3, SkillKind.Normal, 5),
            new Row("scout", "Field Kitchen", 3, SkillKind.Normal, 3),
            new Row("scout", "Farsight", 3, SkillKind.Normal, 3),
            new Row("scout", "Vigor", 3, SkillKind.Normal, 5),
        };

        public static readonly (string Prefab, string Primary, string Secondary)[] Heroes =
        {
            ("Ally_MC01", "warrior", null),
            ("Ally_MC02", "guardian", null),
            ("Ally_MC03", "warrior", null),
            ("Ally_MC04", "archer", null),
            ("Ally_MC05", "elementalist", null),
            ("Ally_MC06", "healer", null),
            ("Ally_MC07", "bard", null),
            ("Ally_MC08", "occultist", null),
            ("Ally_MC09", "rogue", null),
            ("Ally_MC10", "commander", null),
            ("Ally_MC11", "scout", null),
            ("Ally_MC12", "guardian", null),
            ("Ally_MC13", "healer", null),
            ("Ally_MC14", "archer", null),
            ("Ally_MC15", "elementalist", null),
            ("Ally_MC16", "bard", null),
            ("Ally_MC17", "occultist", null),
            ("Ally_MC18", "rogue", null),
            ("Ally_MC19", "commander", null),
            ("Ally_MC20", "scout", null),
            ("Ally_MC21", "warrior", "guardian"),
            ("Ally_MC22", "healer", "elementalist"),
            ("Ally_MC23", "archer", "scout"),
            ("Ally_MC24", "rogue", "occultist"),
        };
    }
}
